### PR TITLE
Cleanup python setup files

### PR DESCRIPTION
**Pull request by mbanth**
Remove incorrect comment in requirements.txt.  Also remove the tools_xmostest entries since Build.pl and setupEnv handle the xmostest dependencies.

### CODE REVIEW

**Review by BrennanGit — APPROVED** [review]
I'm happy, assuming you've confirmed that the tests can indeed be run with this setup. Unfortunately the Jenkinsfile doesn't test this.

**Comment by mbanth** [comment]
> I'm happy, assuming you've confirmed that the tests can indeed be run with this setup. Unfortunately the Jenkinsfile doesn't test this.

I have not confirmed that the tests will run with this setup.  If the Jenkinsfile doesn't run the tests, that's an oversight which I want to correct as part of this PR.  If you know of another Jenkinsfile that provides a good example, I will modify this one in a similar fashion and then we can work on it until it's fit for purpose.

**Comment by BrennanGit** [comment]
lib_logging does have this:
```
    stage('Tests') {
      steps {
        runXmostest("${REPO}", 'tests')
      }
    }
```

**Comment by mbanth** [comment]
> I'm happy, assuming you've confirmed that the tests can indeed be run with this setup. Unfortunately the Jenkinsfile doesn't test this.

I'm a bit confused (not that that's anything new).  The lib_xassert Jenkinsfile has the exact same stage as you mentioned from lib_logging.  I can see in the console log of the successful pr-merge run that four tests were run and all passed.  Did you mean some testing beyond these four tests?

**Comment by BrennanGit** [comment]
You're absolutely right, I must have been getting my PRs confused. I'd say thats confirmed working then.

**Pull request merged**
